// components/GallerySection.tsx
"use client";
import Image from "next/image";
import { useState } from "react";
import { X, ChevronLeft, ChevronRight } from "lucide-react";
import useIntersectionObserver from "@/hooks/useIntersectionObserver";
export default function GallerySection() {
  const [selectedImage, setSelectedImage] = useState<string | null>(null);
  const [ref, isVisible] = useIntersectionObserver();

  const categories = [
    {
      id: "office",
      title: "Office Buildings",
      description:
        "Professional fire safety installations for corporate offices and business centers",
      featured: "/commercial-fire-installation.png",
      projects: [
        {
          id: 1,
          title: "Corporate Headquarters",
          image: "/commercial-fire-installation.png",
        },
        {
          id: 2,
          title: "Business Center Complex",
          image: "/warehouse-fire-system.png",
        },
        {
          id: 3,
          title: "High-Rise Office Tower",
          image: "/retail-fire-extinguisher.png",
        },
      ],
    },
    {
      id: "residential",
      title: "Residential Buildings",
      description:
        "Comprehensive fire protection for apartments, condos, and residential complexes",
      featured: "/residential-fire-safety.png",
      projects: [
        {
          id: 4,
          title: "Apartment Complex",
          image: "/residential-fire-safety.png",
        },
        {
          id: 5,
          title: "Condominium Tower",
          image: "/apartment-fire-system.png",
        },
        {
          id: 6,
          title: "Senior Living Facility",
          image: "/kitchen-fire-extinguisher.png",
        },
      ],
    },
    {
      id: "government",
      title: "Government Buildings",
      description:
        "Specialized fire safety systems for municipal and federal government facilities",
      featured: "/industrial-fire-system.png",
      projects: [
        {
          id: 7,
          title: "City Hall Complex",
          image: "/industrial-fire-system.png",
        },
        {
          id: 8,
          title: "Federal Office Building",
          image: "/chemical-plant-fire-safety.png",
        },
        {
          id: 9,
          title: "Courthouse Facility",
          image: "/power-plant-fire-system.png",
        },
      ],
    },
    {
      id: "schools",
      title: "Schools & Educational",
      description:
        "Safe learning environments with comprehensive fire protection systems",
      featured: "/warehouse-fire-system.png",
      projects: [
        {
          id: 10,
          title: "Elementary School",
          image: "/warehouse-fire-system.png",
        },
        {
          id: 11,
          title: "University Campus",
          image: "/retail-fire-extinguisher.png",
        },
        {
          id: 12,
          title: "Community College",
          image: "/commercial-fire-installation.png",
        },
      ],
    },
    {
      id: "warehouses",
      title: "Warehouses & Industrial",
      description:
        "Heavy-duty fire suppression systems for storage and manufacturing facilities",
      featured: "/chemical-plant-fire-safety.png",
      projects: [
        {
          id: 13,
          title: "Distribution Center",
          image: "/chemical-plant-fire-safety.png",
        },
        {
          id: 14,
          title: "Manufacturing Plant",
          image: "/power-plant-fire-system.png",
        },
        {
          id: 15,
          title: "Cold Storage Facility",
          image: "/industrial-fire-system.png",
        },
      ],
    },
  ];

  const scrollGallery = (categoryId: string, direction: "left" | "right") => {
    const gallery = document.getElementById(`gallery-${categoryId}`);
    if (gallery) {
      const scrollAmount = 320;
      gallery.scrollBy({
        left: direction === "left" ? -scrollAmount : scrollAmount,
        behavior: "smooth",
      });
    }
  };

  return (
    <section id="gallery" className="py-20 bg-gray-50" ref={ref}>
      {isVisible && (
        <div
          className={`transition-all duration-700 ${
            isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-10"
          }`}
        >
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="text-center mb-16" data-aos="fade-up">
              <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6">
                Our Fire Safety Projects
              </h2>
              <p className="text-xl text-gray-600 max-w-3xl mx-auto">
                See how we've protected businesses and homes with professional
                fire extinguisher installations and safety systems.
              </p>
            </div>

            <div className="space-y-20">
              {categories.map((category, categoryIndex) => (
                <div
                  key={category.id}
                  className="relative"
                  data-aos="fade-up"
                  data-aos-delay={categoryIndex * 200}
                >
                  {/* Category Header */}
                  <div className="mb-8">
                    <h3 className="text-3xl font-bold text-gray-900 mb-2">
                      {category.title}
                    </h3>
                    <p className="text-lg text-gray-600">
                      {category.description}
                    </p>
                  </div>

                  {/* Featured Project and Gallery */}
                  <div className="grid lg:grid-cols-2 gap-8 items-start">
                    {/* Featured Large Image */}
                    <div className="relative group">
                      <div
                        className="relative overflow-hidden rounded-2xl shadow-2xl cursor-pointer w-full h-80 lg:h-96"
                        onClick={() => setSelectedImage(category.featured)}
                      >
                        <Image
                          src={category.featured || "/placeholder.svg"}
                          alt={`Featured ${category.title} project`}
                          fill
                          className="object-cover group-hover:scale-105 transition-transform duration-700"
                        />
                        <div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                          <div className="absolute bottom-6 left-6 text-white">
                            <span className="text-sm bg-red-600 px-3 py-1 rounded-full mb-2 inline-block">
                              Featured
                            </span>
                            <h4 className="text-xl font-bold">
                              {
                                category.projects.find(
                                  (p) => p.image === category.featured
                                )?.title
                              }
                            </h4>
                          </div>
                        </div>
                      </div>
                    </div>

                    {/* Horizontal Scrolling Gallery */}
                    <div className="relative">
                      <div className="flex items-center justify-between mb-4">
                        <h4 className="text-xl font-semibold text-gray-900">
                          More Projects
                        </h4>
                        <div className="flex gap-2">
                          <button
                            onClick={() => scrollGallery(category.id, "left")}
                            className="p-2 rounded-full bg-white shadow-md hover:shadow-lg transition-shadow duration-200"
                            aria-label="Scroll left"
                          >
                            <ChevronLeft size={20} className="text-gray-600" />
                          </button>
                          <button
                            onClick={() => scrollGallery(category.id, "right")}
                            className="p-2 rounded-full bg-white shadow-md hover:shadow-lg transition-shadow duration-200"
                            aria-label="Scroll right"
                          >
                            <ChevronRight size={20} className="text-gray-600" />
                          </button>
                        </div>
                      </div>

                      <div
                        id={`gallery-${category.id}`}
                        className="flex gap-4 overflow-x-auto scrollbar-hide pb-4"
                        style={{
                          scrollbarWidth: "none",
                          msOverflowStyle: "none",
                        }}
                      >
                        {category.projects.map((project, index) => (
                          <div
                            key={project.id}
                            className="flex-shrink-0 w-72 group cursor-pointer"
                            onClick={() => setSelectedImage(project.image)}
                          >
                            <div className="relative overflow-hidden rounded-xl shadow-lg hover:shadow-xl transition-all duration-300">
                              <Image
                                src={project.image || "/placeholder.svg"}
                                alt={project.title}
                                width={600}
                                height={400}
                                className="w-full h-48 object-cover group-hover:scale-110 transition-transform duration-500"
                              />

                              <div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                                <div className="absolute bottom-4 left-4 text-white">
                                  <h5 className="font-semibold text-sm">
                                    {project.title}
                                  </h5>
                                </div>
                              </div>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>

                  {/* Divider */}
                  {categoryIndex < categories.length - 1 && (
                    <div className="mt-16 border-t border-gray-200"></div>
                  )}
                </div>
              ))}
            </div>

            {/* Lightbox Modal */}
            {selectedImage && (
              <div
                className="fixed inset-0 bg-black/90 z-50 flex items-center justify-center p-4"
                onClick={() => setSelectedImage(null)}
              >
                <div
                  className="relative max-w-4xl max-h-full"
                  onClick={(e) => e.stopPropagation()}
                >
                  <button
                    onClick={() => setSelectedImage(null)}
                    className="absolute top-4 right-4 z-10 bg-black/50 hover:bg-black/70 text-white rounded-full p-2 transition-all duration-200 backdrop-blur-sm"
                    aria-label="Close modal"
                  >
                    <X size={24} />
                  </button>
                  <Image
                    src={selectedImage || "/placeholder.svg"}
                    alt="Gallery image"
                    fill
                    className="object-contain rounded-lg"
                  />
                </div>
              </div>
            )}
          </div>{" "}
        </div>
      )}

      {/* Add custom scrollbar hiding styles */}
      <style jsx>{`
        .scrollbar-hide::-webkit-scrollbar {
          display: none;
        }
      `}</style>
    </section>
  );
}

// components/vue components/GallerySection.vue
<template>
  <section id="gallery" class="py-20 bg-muted">
    <div class="container mx-auto px-4">
      <!-- Section Header -->
      <div class="text-center mb-16" data-aos="fade-up">
        <h2 class="text-4xl md:text-5xl font-bold text-foreground mb-6 font-serif">
          Our Portfolio
        </h2>
        <p class="text-xl text-muted-foreground max-w-3xl mx-auto leading-relaxed">
          Explore our successful projects and see how we've helped businesses achieve their goals.
        </p>
      </div>
      
      <!-- Gallery Tabs -->
      <div class="flex flex-wrap justify-center gap-4 mb-12" data-aos="fade-up" data-aos-delay="200">
        <button 
          v-for="category in categories" 
          :key="category"
          @click="activeCategory = category"
          :class="[
            'px-6 py-3 rounded-full font-semibold transition-all duration-300',
            activeCategory === category 
              ? 'bg-accent text-accent-foreground shadow-lg' 
              : 'bg-card text-card-foreground hover:bg-accent/10 border border-border'
          ]"
        >
          {{ category }}
        </button>
      </div>
      
      <!-- Gallery Grid -->
      <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
        <div 
          v-for="(item, index) in filteredGallery" 
          :key="item.id"
          :data-aos="'fade-up'"
          :data-aos-delay="index * 100"
          class="group relative overflow-hidden rounded-2xl shadow-lg hover:shadow-2xl transition-all duration-300 cursor-pointer"
          @click="openLightbox(item)"
        >
          <div class="aspect-square overflow-hidden">
            <img 
              :src="item.image" 
              :alt="item.title"
              class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500"
            />
          </div>
          
          <!-- Overlay -->
          <div class="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300">
            <div class="absolute bottom-0 left-0 right-0 p-6">
              <h3 class="text-white font-bold text-xl mb-2 font-serif">{{ item.title }}</h3>
              <p class="text-white/90 text-sm">{{ item.description }}</p>
              <div class="mt-3">
                <span class="inline-block bg-accent/20 text-accent-foreground px-3 py-1 rounded-full text-xs font-medium">
                  {{ item.category }}
                </span>
              </div>
            </div>
          </div>
          
          <!-- View Icon -->
          <div class="absolute top-4 right-4 w-10 h-10 bg-white/20 backdrop-blur-sm rounded-full flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
            <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path>
            </svg>
          </div>
        </div>
      </div>
    </div>
    
    <!-- Lightbox Modal -->
    <div 
      v-if="lightboxOpen" 
      class="fixed inset-0 z-50 bg-black/90 flex items-center justify-center p-4"
      @click="closeLightbox"
    >
      <div class="relative max-w-4xl max-h-full">
        <img 
          :src="selectedImage?.image" 
          :alt="selectedImage?.title"
          class="max-w-full max-h-full object-contain rounded-lg"
        />
        <button 
          @click="closeLightbox"
          class="absolute top-4 right-4 w-10 h-10 bg-white/20 backdrop-blur-sm rounded-full flex items-center justify-center text-white hover:bg-white/30 transition-colors"
        >
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
          </svg>
        </button>
        <div class="absolute bottom-4 left-4 right-4 text-center">
          <h3 class="text-white font-bold text-2xl mb-2 font-serif">{{ selectedImage?.title }}</h3>
          <p class="text-white/90">{{ selectedImage?.description }}</p>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import { ref, computed } from 'vue'

const activeCategory = ref('All')
const lightboxOpen = ref(false)
const selectedImage = ref(null)

const categories = ['All', 'Consulting', 'Marketing', 'Technology', 'Finance']

const galleryItems = [
  {
    id: 1,
    title: 'Corporate Strategy Redesign',
    description: 'Complete business strategy overhaul for a Fortune 500 company',
    category: 'Consulting',
    image: '/placeholder.svg?height=400&width=400'
  },
  {
    id: 2,
    title: 'Digital Marketing Campaign',
    description: 'Award-winning social media campaign that increased engagement by 300%',
    category: 'Marketing',
    image: '/placeholder.svg?height=400&width=400'
  },
  {
    id: 3,
    title: 'Cloud Infrastructure Migration',
    description: 'Seamless migration of legacy systems to modern cloud architecture',
    category: 'Technology',
    image: '/placeholder.svg?height=400&width=400'
  },
  {
    id: 4,
    title: 'Financial Planning System',
    description: 'Custom financial planning platform for investment management',
    category: 'Finance',
    image: '/placeholder.svg?height=400&width=400'
  },
  {
    id: 5,
    title: 'Brand Identity Development',
    description: 'Complete brand redesign and identity system for tech startup',
    category: 'Marketing',
    image: '/placeholder.svg?height=400&width=400'
  },
  {
    id: 6,
    title: 'Process Automation',
    description: 'Automated workflow system reducing manual tasks by 80%',
    category: 'Technology',
    image: '/placeholder.svg?height=400&width=400'
  },
  {
    id: 7,
    title: 'Market Analysis Report',
    description: 'Comprehensive market research and competitive analysis',
    category: 'Consulting',
    image: '/placeholder.svg?height=400&width=400'
  },
  {
    id: 8,
    title: 'Investment Portfolio',
    description: 'Diversified investment strategy yielding 15% annual returns',
    category: 'Finance',
    image: '/placeholder.svg?height=400&width=400'
  },
  {
    id: 9,
    title: 'E-commerce Platform',
    description: 'Custom e-commerce solution with advanced analytics',
    category: 'Technology',
    image: '/placeholder.svg?height=400&width=400'
  }
]

const filteredGallery = computed(() => {
  if (activeCategory.value === 'All') {
    return galleryItems
  }
  return galleryItems.filter(item => item.category === activeCategory.value)
})

const openLightbox = (item) => {
  selectedImage.value = item
  lightboxOpen.value = true
  document.body.style.overflow = 'hidden'
}

const closeLightbox = () => {
  lightboxOpen.value = false
  selectedImage.value = null
  document.body.style.overflow = 'auto'
}
</script>
